# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'coin' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for coin
pod ‘Parse’
pod "RFKeyboardToolbar", "~> 1.3"
pod "TLRadioButton"
pod 'SCLAlertView-Objective-C', '~> 1.1'
pod "EChart"
pod 'IQKeyboardManager'
pod ‘FSCalendar’
end
